<?php

namespace AppBundle\Repository;

/**
 * ContactTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
