<?php

namespace AppBundle\Repository;

/**
 * DurationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DurationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
