<?php

namespace AppBundle\Repository;

/**
 * LessonTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
