<?php

namespace AppBundle\Repository;

/**
 * StudiesLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudiesLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
