<?php

namespace AppBundle\Repository;

/**
 * SummaryStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SummaryStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
