<?php

namespace AppBundle\Repository;

/**
 * UserLessonStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLessonStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
