<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserWithoutPassword(){
        $fields = array('d.id', 'd.username', 'd.email');

        $query = $this->getEntityManager()->createQueryBuilder();
        $query = $this->createQueryBuilder('d')
            ->select($fields)
            ->getQuery();

        return $query->execute();
    }
}
