<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersAskingTrainer(){
        $query = $this->getEntityManager()->createQueryBuilder()
            -> select('t')
            ->from('AppBundle:User', 't')
            ->where('t.askTrainer IS NOT NULL')
            ->andWhere('t.answerTrainer IS NULL')
            ->getQuery();

        return $query->execute();
    }
}
