<?php

namespace AppBundle\Repository;

/**
 * UserLessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLessonRepository extends \Doctrine\ORM\EntityRepository
{
}
