# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            methods: [POST]
            pattern: ^/login$
            anonymous: true
            stateless: true
            guard:
                authenticators:
                   - AppBundle\Controller\Security\Authenticator\UserLoginAuthenticator

        main:
            anonymous: ~
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Controller\Security\Authenticator\TokenAuthenticator

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

